# Generated by Django 3.2.13 on 2023-01-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField()),
                ('addedOn', models.TimeField(auto_now_add=True)),
                ('addedBy', models.BigIntegerField()),
                ('updatedOn', models.TimeField(auto_now=True)),
                ('updatedBy', models.BigIntegerField()),
                ('deletedOn', models.TimeField(auto_now=True)),
                ('deletedBy', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('image', models.ImageField(upload_to='featured_image/%Y/%m/%d/')),
                ('status', models.SmallIntegerField(default=1)),
                ('addedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('addedBy', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Initial added Date')),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.BigIntegerField(blank=True, null=True)),
                ('deletedOn', models.DateTimeField(auto_now=True)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.branch')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('BM', 'Branch Manager'), ('ST', 'Staff')], max_length=5)),
                ('mobile', models.CharField(max_length=127)),
                ('status', models.SmallIntegerField(default=1)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('addedBy', models.BigIntegerField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.BigIntegerField(blank=True, null=True)),
                ('deletedOn', models.TimeField(auto_now=True)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.branch')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('age', models.CharField(blank=True, max_length=1023, null=True)),
                ('email', models.CharField(blank=True, max_length=1023, null=True)),
                ('aadhar', models.CharField(max_length=1023, unique=True)),
                ('fatherName', models.CharField(max_length=255)),
                ('motherName', models.CharField(max_length=255)),
                ('disabledPerson', models.BooleanField(default=False)),
                ('suretyName', models.CharField(max_length=255)),
                ('suretyAge', models.CharField(blank=True, max_length=1023, null=True)),
                ('suretyAadhar', models.CharField(blank=True, max_length=1023, null=True, unique=True)),
                ('suretyMobile', models.CharField(blank=True, max_length=1023, null=True, unique=True)),
                ('occupation', models.CharField(choices=[('agriculture', 'Agriculture'), ('tailor', 'Tailor'), ('wages', 'Wages'), ('driver', 'Driver'), ('salaried', 'Salaried')], max_length=200)),
                ('monthlyIncome', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(choices=[('8-grade', '8 Grade'), ('10-grade', '10 Grade'), ('12-grade', '12 Grade'), ('UG', 'Under Graduate'), ('PD', 'Post Graduate'), ('others', 'Others'), ('diploma', 'Diploma')], max_length=200)),
                ('religion', models.CharField(choices=[('hindu', 'HINDU'), ('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], max_length=200)),
                ('martialDetails', models.CharField(choices=[('married', 'Married'), ('unmarried', 'UnMarried'), ('widow', 'Widow')], max_length=200)),
                ('houseDetails', models.CharField(choices=[('own', 'Own House'), ('rent', 'Rent House'), ('lease', 'Lease House')], max_length=200)),
                ('yearsOfHouse', models.PositiveIntegerField()),
                ('adultCount', models.PositiveIntegerField(default=0)),
                ('childrenCount', models.PositiveIntegerField(default=0)),
                ('mobile', models.CharField(blank=True, max_length=1023, null=True)),
                ('panNo', models.CharField(blank=True, max_length=1023, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('addedOn', models.TimeField(auto_now_add=True)),
                ('addedBy', models.BigIntegerField(blank=True, null=True)),
                ('updatedOn', models.TimeField(auto_now=True)),
                ('updatedBy', models.BigIntegerField(blank=True, null=True)),
                ('deletedOn', models.DateTimeField(auto_now=True, null=True)),
                ('deletedBy', models.BigIntegerField(blank=True, null=True)),
                ('centerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.center')),
                ('suretyRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.relationship')),
            ],
        ),
    ]
