# Generated by Django 3.2.13 on 2023-03-14 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField()),
                ('createdBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_created_user', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tamilName', models.CharField(max_length=255)),
                ('shortName', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('status', models.SmallIntegerField(default=1)),
                ('dayOrder', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=50)),
                ('time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.branch')),
                ('createdBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_created_user', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_updated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('BM', 'Branch Manager'), ('ST', 'Staff')], max_length=5)),
                ('blood_type', models.CharField(choices=[('ab+', 'AB+'), ('ab-', 'AB-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-')], max_length=5)),
                ('mobile', models.CharField(max_length=127)),
                ('status', models.SmallIntegerField(default=1)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.branch')),
                ('createdBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_created_user', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_updated_user', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tamilName', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('age', models.CharField(blank=True, max_length=1023, null=True)),
                ('email', models.CharField(blank=True, max_length=1023, null=True)),
                ('aadhar', models.CharField(max_length=1023, unique=True)),
                ('fatherName', models.CharField(max_length=255)),
                ('motherName', models.CharField(max_length=255)),
                ('disabledPerson', models.BooleanField(default=False)),
                ('suretyName', models.CharField(max_length=255)),
                ('suretyAge', models.CharField(blank=True, max_length=1023, null=True)),
                ('suretyAadhar', models.CharField(blank=True, max_length=1023, null=True, unique=True)),
                ('suretyMobile', models.CharField(blank=True, max_length=1023, null=True, unique=True)),
                ('occupation', models.CharField(choices=[('agriculture', 'Agriculture'), ('tailor', 'Tailor'), ('wages', 'Wages'), ('driver', 'Driver'), ('salaried', 'Salaried')], max_length=200)),
                ('monthlyIncome', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(choices=[('8-grade', '8 Grade'), ('10-grade', '10 Grade'), ('12-grade', '12 Grade'), ('UG', 'Under Graduate'), ('PD', 'Post Graduate'), ('others', 'Others'), ('diploma', 'Diploma')], max_length=200)),
                ('religion', models.CharField(choices=[('hindu', 'HINDU'), ('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], max_length=200)),
                ('martialDetails', models.CharField(choices=[('married', 'Married'), ('unmarried', 'UnMarried'), ('widow', 'Widow')], max_length=200)),
                ('houseDetails', models.CharField(choices=[('own', 'Own House'), ('rent', 'Rent House'), ('lease', 'Lease House')], max_length=200)),
                ('yearsOfHouse', models.PositiveIntegerField()),
                ('adultCount', models.PositiveIntegerField(default=0)),
                ('childrenCount', models.PositiveIntegerField(default=0)),
                ('mobile', models.CharField(blank=True, max_length=1023, null=True)),
                ('panNo', models.CharField(blank=True, max_length=1023, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('centerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.center')),
                ('createdBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_created_user', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suretyRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.relationship')),
                ('updatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
