# Generated by Django 3.2.13 on 2023-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='branchId',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddField(
            model_name='center',
            name='dayOrder',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=50),
            preserve_default=False,
        ),
    ]
