# Generated by Django 4.1.4 on 2022-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
