# Generated by Django 4.1.7 on 2023-03-17 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0003_auto_20230314_0218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="age",
        ),
        migrations.AddField(
            model_name="member",
            name="yearsOfService",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="suretyAge",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="suretyRelation",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("son", "Son"),
                    ("daughter", "Daughter"),
                    ("brother", "Brother"),
                    ("father-in-law", "Father In Law"),
                    ("mother-in-law", "Mother In Law"),
                ],
                max_length=200,
            ),
        ),
    ]
