# Generated by Django 3.2.13 on 2023-02-11 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_center_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
