# Generated by Django 4.1.7 on 2023-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0004_remove_member_age_member_yearsofservice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(default="", max_length=2055),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
