# Generated by Django 3.2.13 on 2023-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_role_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='shortName',
            field=models.CharField(default='DGL-1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='tamilName',
            field=models.CharField(default='need to add', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='uniqueName',
            field=models.IntegerField(default='test'),
            preserve_default=False,
        ),
    ]
