# Generated by Django 4.1.7 on 2023-03-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misc", "0005_member_address_member_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="deletedBy",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_deleted_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
