# Generated by Django 3.2.13 on 2023-03-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_auto_20230313_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='uniqueName',
            field=models.CharField(max_length=200),
        ),
    ]
