# Generated by Django 3.2.13 on 2023-03-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_alter_center_uniquename'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tamilName',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
